import Navbar from "../components/Navbar"
import Footer from "../components/Footer"
export const metadata = {
  title: 'StartExs.com',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-black mx-2">
      <Navbar/>
        {children}
      <Footer/>
        </body>
    </html>
  )
}
